// Generated by CoffeeScript 1.8.0
(function() {
  var Address, Request;

  Request = require('./request');

  module.exports = Address = (function() {
    function Address(url) {
      this.request = new Request(url);
    }

    Address.prototype.balance = function(address, cb) {
      return this.request.get('addresses/' + address, cb);
    };

    Address.prototype.transactions = function(address, params, cb) {
      var path;
      path = 'addresses/' + address + '/transactions';
      return this.request.get(path, params, cb);
    };

    Address.prototype.unspent_outputs = function(address, params, cb) {
      var path;
      path = 'addresses/' + address + '/unspent_outputs';
      return this.request.get(path, params, cb);
    };

    return Address;

  })();

}).call(this);
