// Generated by CoffeeScript 1.8.0
(function() {
  var Request, Transaction;

  Request = require('./request');

  module.exports = Transaction = (function() {
    function Transaction(url) {
      this.request = new Request(url);
    }

    Transaction.prototype.get = function(hash, cb) {
      return this.request.get('transactions/' + hash, cb);
    };

    Transaction.prototype.unconfirmed = function(params, cb) {
      return this.request.get('transactions/unconfirmed', params, cb);
    };

    Transaction.prototype.broadcast = function(hex, cb) {
      return this.request.post('transactions', {
        hex: hex
      }, cb);
    };

    return Transaction;

  })();

}).call(this);
