// Generated by CoffeeScript 1.8.0
(function() {
  var Addresses, Blocks, Toshi, Transactions;

  Addresses = require('./modules/addresses');

  Blocks = require('./modules/blocks');

  Transactions = require('./modules/transactions');

  module.exports = Toshi = (function() {
    function Toshi(url) {
      url = url != null ? url : 'https://bitcoin.toshi.io';
      this.url = url += '/api/v0/';
      this.address = new Addresses(this.url);
      this.block = new Blocks(this.url);
      this.transaction = new Transactions(this.url);
    }

    return Toshi;

  })();

}).call(this);
